name: Build and test 

on: push

env:
  NODE_VERSION: 16.x

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install, build
      run: |
        yarn bootstrap
        yarn build
    - name: Run tests
      run: yarn test

